### ISSUE TITLE
fix empty list message

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#85]
Currently in ./Phylotastic_Mobile_Application/www/templates/species_names_list_view.html there is an error message activated when picking "get tree" for an empty list.  The message says "There is no any list of species names".  The way of saying this in English would be either "There is not any list" (singular) or "There are not any names" (plural).  

I would recommend instead "The list is empty.  See HowTo [link] for how to add names."

**Comment by thanhnh-infinity** [comment]
I fixed them . Could you update  our newest mobile app ?

**Comment by arlin** [comment]
OK, what I am seeing now is that a message appears automatically for an empty list, indicating that the list is empty and directing the user to "How To" for how to add names.  I think this is helpful. Another way to state it would be "Empty list: click camera icon to add names (see How To)." 

Then, when I click on "Get Tree", I see a message saying "We are sorry.  We could not find phylogeny information for these species."   See the image below.  A more appropriate message would be "Empty list: add names to the list before trying to get a tree!" 

![img_2412](https://cloud.githubusercontent.com/assets/1659198/18476679/032b9b72-7999-11e6-88ec-cbd5fae5940b.PNG)

**Comment by arlin** [comment]
This is not a priority so I'm moving this into backlog.  However, I now realize it is a mistake to send the user immediately to "HowTo" instead of just telling the user what to do, like this: 

"(Empty list) Click the camera icon to build a list of names from signage (see HowTo [link])."

Also, we still have a misleading message if the user clicks "Get Tree" for an empty list.  The message says "We could not find phylogeny information for these species."  A less confusing message would be "Your list is empty!  Add names before requesting a tree." with an "OK" button to dismiss the pop-up.
